import{_ as i,c as e,a,o}from"./app-BDA3eys7.js";const t="/assets/image-spKkLYtQ.png",u="/assets/image-1-DujErSJq.png",c={};function s(p,l){return o(),e("div",null,[...l[0]||(l[0]=[a('<h1 id="_3d打印笔记" tabindex="-1"><a class="header-anchor" href="#_3d打印笔记"><span>3d打印笔记</span></a></h1><h2 id="看图" tabindex="-1"><a class="header-anchor" href="#看图"><span>看图</span></a></h2><blockquote><p>记录看到的有趣的制作</p></blockquote><ul><li>伸缩夹<code>基本上就是杠杆，但是不是直的杠杆</code></li><li>环形花洒<code>形状是环形，水是从中间出来的，像洗车一样</code></li><li>布质链甲</li><li>棘轮发条<code>像手表一样，会嘎嘎响</code></li></ul><h2 id="作图" tabindex="-1"><a class="header-anchor" href="#作图"><span>作图</span></a></h2><ul><li>开启自动投影边以用作参考</li><li>创建零部件</li><li>创建草图 <ul><li>创建矩形（两点矩形，输入数值，完成草图）</li><li>创建3d矩形<code>切换视图，拉伸</code></li><li>确定相对位置（创建-草图尺寸）</li><li>批量复制（阵列）</li></ul></li><li>掏空一部分（）</li><li>创建空心圆柱（构造（确定圆心和半径）） <ul><li>创建同心圆（修改-偏移）</li></ul></li><li>圆角</li><li>送到切片软件里（打印机软件） <ul><li>文件-3d打印</li></ul></li></ul><h2 id="学习制作" tabindex="-1"><a class="header-anchor" href="#学习制作"><span>学习制作</span></a></h2><h3 id="制作第二个" tabindex="-1"><a class="header-anchor" href="#制作第二个"><span>制作第二个</span></a></h3><blockquote><p>计划是，打印一个酒杯，用来放置葡萄 测量：直径是2.5，长是3，我希望能卡住，所以是1.2的半径，1.5的长最多，下面就按照1：1：1的设计</p></blockquote><ul><li>新建零部件（装配-新建零部件）</li><li>创建旋转体 <ul><li>插入-画布-选择图片-选择zx面-确定</li><li>选中画布，设置尺寸，参考位置</li><li>钢笔工具描边（点-样条曲线-拟合）</li><li>完成草图</li><li>创建-旋转-选择z轴</li></ul></li><li>掏空 <ul><li>抽壳，选择方向</li><li>分析确定有没有抽壳成功</li></ul></li><li>检验-截面分析-观察有没有抽壳成功（左边的眼睛可以关闭）</li><li>不够的地方用草图，重新加上或者剪掉</li><li>增加外观 <ul><li>物理材料，</li><li>外观（颜色）</li></ul></li><li>设计-渲染-渲染</li></ul><h3 id="制作一颗螺丝" tabindex="-1"><a class="header-anchor" href="#制作一颗螺丝"><span>制作一颗螺丝</span></a></h3><blockquote><p>就M3 的螺丝和螺母吧，看看能不能打上。 螺丝为什么是六边形 <img src="'+t+'" alt="alt text"><img src="'+u+'" alt="alt text"></p></blockquote><ul><li>创建多边形（创建-多边形-外切多边形）</li><li>切角（选择xz轴-创建-直线画三角形-完成-旋转）</li><li>复制（构造-中间平面）</li><li>创建-镜像（特征）</li><li>打孔（创建-孔-实体化）</li></ul><blockquote><p>打孔里的M3怎么只有2mm，难道M3指的是螺母的直径</p></blockquote><ul><li>ok，检查了下，发现要选4mm，外面是把直径看成半径了</li><li>外观（实体-物理材料）</li><li>渲染</li></ul><blockquote><p>螺丝的话，不知道怎么画自攻螺丝</p></blockquote><ul><li>我再给它加个盖子</li><li>以及仿真（也许是） <ul><li>装配（线性和组合）</li><li>构造-运动连接（选择旋转）</li></ul></li></ul><blockquote><p>打印出的盖子，没有办法安装，但是螺丝可以连接到金属的螺母上，但是打印的螺母就不够大了，而且没有十字的头</p></blockquote><ul><li>我换成孔的螺纹，而不是自己画图出的螺纹</li></ul><blockquote><p>但是打印出来的螺母，要么大一点，要么小一点装补上。我觉得是需要选择3.5*0.6 的试试看，还不行的话，就算了，会差个两毫米，不行的话，就打印一个大点的，避免误差好了</p></blockquote><ul><li>最后一次，3.0*0.35</li></ul><blockquote><p>破案了，是自攻和别的螺纹不一样，打印的3.5能比较容易的进入金属件，但是3.0就不太行。估计是精度的问题，不去考虑它了</p></blockquote><h3 id="完成一个盒子-门轴的制作" tabindex="-1"><a class="header-anchor" href="#完成一个盒子-门轴的制作"><span>完成一个盒子，门轴的制作</span></a></h3><blockquote><p>2.5 x 3 x 2 的一个放螺丝的盒子 关键是轴和卡扣</p></blockquote><ul><li>创建一个盒子，但是被切割 <ul><li>草图-拉伸</li><li>构造-偏移平面</li><li>修改-分割实体</li></ul></li><li>创建轴 <ul><li>标注-创建联动尺寸（用来锁定）</li><li>打印机不需要支持是45°（视频说的）</li><li>拉伸，创建新的实体</li></ul></li><li>切割 <ul><li>减去</li><li>选中实体，移除不需要的部分</li></ul></li><li>旋转 <ul><li>从实体中创建零部件</li><li>装配-快速连接-检查问题</li></ul></li><li>组装 <ul><li>实体-拖动到零部件中，不知道为什么不可以</li><li>我把实体合并，然后单独生成零部件</li><li>然后再使用装配，可以决定展开的样子</li></ul></li></ul><blockquote><p>现在放过去验证，看转轴好不好，然后再增加卡扣的功能 我还想给debug board打印一些盒子 我还想打印一个奶子，但是腰不行了，等下还要整理，先去吃饭</p></blockquote><ul><li>尺寸做错了，喷头的精度是0.4mm，下次不要出现几毫米的的了，好歹也做成10mm的精度</li></ul><h3 id="制作卡扣" tabindex="-1"><a class="header-anchor" href="#制作卡扣"><span>制作卡扣</span></a></h3><ul><li>先做一个盒子出来，相当于复习了前面的内容</li><li>做了一个缝，但是因为太窄，所以，切片上都看不出来，于是加厚了厚度，希望能够合上，上机打印</li></ul><blockquote><p>基本上是ok的，但是不好开口和闭合，而且接缝的问题，没有很好的出现</p></blockquote><h2 id="实践" tabindex="-1"><a class="header-anchor" href="#实践"><span>实践</span></a></h2><h3 id="给开发板制作一个盒子" tabindex="-1"><a class="header-anchor" href="#给开发板制作一个盒子"><span>给开发板制作一个盒子</span></a></h3><ul><li>如果是计算厚度+间隙，则使用2+1</li><li>拉出卡扣（拉伸-角度）</li><li>切割（合并-切割-选择刀具）</li><li>增加公差（修改-偏移面）</li></ul><blockquote><p>第一版结果出来了，基本上是ok的，出现的问题</p></blockquote><ol><li>没有办法安装，因为我是垂直安装，栏杆部分卡住了上下活动的部分，需要删除掉</li><li>充电口部分没有对齐，因为留出的空隙，导致边缘并不是充电口的边缘，也就是边留多了，但是裁剪少了 <ol><li>要么把边长弄短</li><li>要么把开口留大</li></ol></li><li>因为坐标系是从左往右，导致左边的空间留的大，右边的空间留的小，所以整体偏左，但是右边又被卡住 <ol><li>左边电阻的位置没有保护好</li><li>connecter从右边卡住了PCB</li><li>有一个connecter留的口子不对</li></ol></li><li>上面的开大了，不合适</li><li>卡扣扣不住，卡扣画的太小了</li><li>误差留的太大了，考虑要不要重画</li></ol><blockquote><p>修改之后就work了，仍然有一些问题</p></blockquote><ol><li>卡扣使用摩擦力的了，可以，但是有点松，摩擦力小了点</li><li>开口没有很好的缝合，所以参数上还要改一改</li></ol><h4 id="数据" tabindex="-1"><a class="header-anchor" href="#数据"><span>数据</span></a></h4><ul><li><p>93 x 106，我要给0.5mm的误差</p></li><li><p>厚度是1mm, 向下偏移1mm，向上偏移1.6mm，总的高度要4mm，下2，上2</p></li><li><p>侧面厚度，我要3mm</p></li><li><p>底面厚度，要2mm</p></li><li><p>基本上画完了，测量花了些时间</p></li><li><p>还差一些开孔没有弄，可以先弄底座出来，先打印引擎。后面有空再弄，估计明天就可以画出来了</p></li><li><p>底座已经打印了，留0.5的偏移还是大了一些</p><ul><li>下次可以再保守一些</li><li>x轴的距离是对的，几乎完美，y轴的稍微长一些，不明白</li><li>测量的速度需要提升</li></ul></li><li><p>圆角加的太早，影响到了长拉伸，删除掉</p></li><li><p>拉伸一些不合适的尺寸</p></li><li><p>留一个底座，对层数做出设置，让usb底座卡到，不要翘起来</p></li></ul><h4 id="遗留问题" tabindex="-1"><a class="header-anchor" href="#遗留问题"><span>遗留问题</span></a></h4><ul><li>有一个边多留出了0.5mm的重叠，不知道为什么，下次要检查 <ul><li>因为发现板子在抖，所以拉伸了</li></ul></li><li>忘记给指示灯留出位置了 <ul><li>后面因为别人提出了，所以增加了</li></ul></li><li>留出的位置基本ok，可以再优化一部分的位置，比如上下只有1mm，而不是2mm <ul><li>增加了壁厚0.1，摩擦力增加，使得卡的更紧了</li></ul></li><li>下次可以尝试，使用一张图片来弄，而不是用测量的方法</li></ul>',41)])])}const n=i(c,[["render",s]]),r=JSON.parse('{"path":"/posts/CS/3dPrint.html","title":"3d打印笔记","lang":"zh-CN","frontmatter":{"date":"2025-10-18T00:00:00.000Z","category":["CS"],"tag":["3D打印"],"archive":false,"excerpt":"<p> 买了拓竹的3d打印机，想自己画图打印</p>"},"git":{"updatedTime":1760765850000,"contributors":[{"name":"loker","username":"loker","email":"blemmyes@foxmail.com","commits":2,"url":"https://github.com/loker"}],"changelog":[{"hash":"c62f15c8c0d2edec2da0d2da6b3dae97d8d59b0e","time":1760765850000,"email":"blemmyes@foxmail.com","author":"loker","message":"补充忘记增加的yml设定"},{"hash":"39719f3b1cf38ac9f9ffca6253f9bd94606dd017","time":1759762536000,"email":"blemmyes@foxmail.com","author":"loker","message":"3d打印的笔记"}]},"filePathRelative":"posts/CS/3dPrint.md"}');export{n as comp,r as data};
